# Generated by Django 5.2.8 on 2025-11-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dadjokes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joke',
            options={},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={},
        ),
        migrations.AlterField(
            model_name='joke',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
