# Generated by Django 5.2.6 on 2025-10-24 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0008_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follower_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='mini_insta.profile'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='mini_insta.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('profile', 'follower_profile')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'profile')},
        ),
    ]
