# Generated by Django 5.2.6 on 2025-12-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio about the doctor.'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='image_url',
            field=models.URLField(blank=True, help_text='Link to a profile image (optional)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
